/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file OpenVRSystem.h
 * @author thetestgame
 * @date 2018-03-09
 */


  INLINE bool OpenVRSystem::get_vr_initialized() const {
    return _vr_initialized;
  }